# aaPanel Apache reverse proxy for Payment Hub
# Path: /www/server/panel/vhost/apache/extension/upays.in/payment.conf

<IfModule mod_proxy.c>
    ProxyPreserveHost On
    ProxyRequests Off

    ProxyPass        /payment/ http://127.0.0.1:8090/
    ProxyPassReverse /payment/ http://127.0.0.1:8090/
</IfModule>
