CREATE TABLE IF NOT EXISTS orders (
    id                  CHAR(36) PRIMARY KEY,
    hub_order_id        VARCHAR(20) NOT NULL UNIQUE,
    merchant_id         CHAR(36) NOT NULL,
    merchant_order_id   VARCHAR(100) NOT NULL,
    payment_token       VARCHAR(64) NOT NULL UNIQUE,
    amount              DECIMAL(12,2) NOT NULL,
    currency            VARCHAR(3) NOT NULL DEFAULT 'INR',
    status              VARCHAR(20) NOT NULL DEFAULT 'pending',
    customer_email      VARCHAR(255) NULL,
    customer_name       VARCHAR(255) NULL,
    customer_phone      VARCHAR(20) NULL,
    product_name        VARCHAR(255) NULL,
    product_description TEXT NULL,
    return_url          VARCHAR(500) NOT NULL,
    webhook_url         VARCHAR(500) NULL,
    phonepe_txn_id      VARCHAR(100) NULL,
    phonepe_response    JSON NULL,
    paid_at             DATETIME(3) NULL,
    expires_at          DATETIME(3) NOT NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_merchant_order (merchant_id, merchant_order_id),
    KEY idx_orders_merchant_status (merchant_id, status, created_at),
    KEY idx_orders_payment_token (payment_token),
    KEY idx_orders_status_expires (status, expires_at),
    CONSTRAINT fk_orders_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
